eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8902
spring:
    application:
        name: EurekaFeign
feign:
   hystrix:
     enabled: true
