eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8905
spring:
    application:
        name: EurekaJdbcCity
    datasource:
        url: jdbc:mysql://10.1.4.13:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: Cpycf@123
        driver-class-name: com.mysql.jdbc.Driver
        
## Mybatis 配置
mybatis:
    typeAliasesPackage: com.EurekaJdbcCity
    mapperLocations: classpath:mapper/*.xml
        
