server:
   application:
     name: EurekaServerApplication-HA

security:
   basic:
      enabled: true
   user:
      name: user
      password: 1
     
---
spring:
   profiles: peer1
server:
   port: 8761
eureka:
   instance:
      hostname: peer1
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://peer2:8762/eureka/
   server:
       enableSelfPreservation: false 

---
spring:
   profiles: peer2
server:
   port: 8762
eureka:
   instance:
      hostname: peer2
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://peer1:8761/eureka/
   server:
       enableSelfPreservation: false
