eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8903
spring:
    application:
        name: EurekaZuul
zuul:
  routes:
    ribbo:
      path: /api-ribbon/**
      serviceId: EurekaServiceRibbon
    feign:
      path: /api-feign/**
      serviceId: EurekaFeign
