eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3001
sidecar:
  port: 3000  
  health-uri: http://localhost:3000/health
spring:
  application:
    name: EurekaSidecar